#pragma once

#include <string>


class CryptoHelpers {
    static const int AES_KEY_SIZE = 32;
    static const int AES_IV_SIZE = 16;

public:
    /**
     * Generates a random 256-bit key for AES encryption.
     * Ideally, this is to be used as a session key. It's generated by a
     * cryptographically secure pseudo-random generator.
     */
    static std::string generate_aes_key();

    /**
     * Encrypts a large string using AES-256 in CBC mode.
     */
    static std::string aes_encrypt(const std::string &key, const std::string &plaintext);

    /**
     * Decrypts an AES encrypted blob.
     */
    static std::string aes_decrypt(const std::string &key, const std::string &encrypted_blob);

    /**
     * Encrypts plaintext using a public key.
     */
    static std::string rsa_encrypt_key(const std::string &pub_key_pem, const std::string &plaintext);

    /**
     * Decrypts the AES key using the Receiver's Private Key.
     */
    static std::string rsa_decrypt_key(const std::string &priv_key_pem, const std::string &encrypted_key);

    /**
     * Signs a message to prove authenticity. It creates a SHA-256 hash
     * of the plaintext and encrypts that with the private key.
     */
    static std::string sign_message(const std::string &priv_key_pem, const std::string &plain_text);

    /**
     * Verifies that a signature matches the data using the Sender's Public Key.
     */
    static bool verify_signature(const std::string &pub_key_pem, const std::string &plain_text,
                                 const std::string &signature);
};
